# Site settings
title: "Hi, I'm Sujal"
description: ""

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sujal Patel"
resume_title:                   "Computer Science Major"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sujal.patel@rutgers.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "551 689 5049"
resume_contact_address:         ""

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "<p>Hi, my name is Sujal Pate, a recent graduate of Rutgers University. At my time of Rutgers, I studied and obtained a a Computer Science (B.S) degree. Currently, I am interning at Collabera Inc, in Basking Ridge, NJ as an Information Technologist Intern. In my free time, I love to read about tech as well as rewind and relax by catching up on Netflix or even going out with friends and family. My passion for tech has started since in Middle School and from there, it only gotten greater and greater. In the meantime, I hope everyone stays safe and I look forward in meeting you guys! -Sujal Patel</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            ""
  #resume_twitter_url:           ""
  #resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/sujal1208"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://patelsujal.com"
  #resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
